// takenlijst_vue/src/components/TaskList.vue
<template>
  <div>
    <ul>
      <TaskItem v-for="taak in taken" :key="taak.id" :taak="taak" @toggle="$emit('toggle', $event)" @remove="$emit('remove', $event)" @update="$emit('update', $event)"/>
    </ul>
    <p v-if="taken.length === 0">Nog geen taken.</p>
  </div>
</template>

<script setup>
import TaskItem from './TaskItem.vue';
defineProps(['taken']);
defineEmits(['toggle', 'remove', 'update']);
</script>

// takenlijst_react/src/components/TaskList.jsx
import TaskItem from './TaskItem';

function TaskList({ taken, onRemove, onToggle, onUpdate }) {
  const items = [];
  for (let i = 0; i < taken.length; i++) {
    items.push(<TaskItem key={taken[i].id} taak={taken[i]} onRemove={onRemove} onToggle={onToggle} onUpdate={onUpdate}/>);
  }

  return (
    <div>
      <ul>{items}</ul>
      {taken.length === 0 && <p>Nog geen taken.</p>}
    </div>
  );
}

export default TaskList;
