// takenlijst_svelte/src/components/TaskItem.svelte
<script>
  export let taak;
  export let onToggle;
  export let onRemove;
  export let onUpdate;

  let bewerkModus = false;
  let bewerktitel = '';

  function startBewerk() { bewerkModus = true; bewerktitel = taak.titel; }

  // Annuleer Update
  function AnnuleerUpdate() { bewerkModus = false; bewerktitel = ''; }

  // opslaan Update
  function opslaanUpdate() {
    const titel = bewerktitel.trim();
    if (!titel) return;
    onUpdate(taak.id, titel);
    bewerkModus = false;
    bewerktitel = '';
  }
</script>

<li class="row prioriteit-{taak.prioriteit}">
  <input type="checkbox" checked={taak.done} on:change={() => onToggle(taak.id)}/>
  {#if !bewerkModus}
    <span class="titel" class:done={taak.done}>{taak.titel}</span>
    <div class="actions">
      <button on:click={startBewerk}>Bewerk</button>
      <button on:click={() => onRemove(taak.id)}>Verwijder</button>
    </div>
  {:else}
    <input bind:value={bewerktitel} on:keyup={(e) => e.key === 'Enter' && opslaanUpdate()}/>
    <div class="actions">
      <button on:click={opslaanUpdate}>Opslaan</button>
      <button on:click={AnnuleerUpdate}>Annuleer</button>
    </div>
  {/if}
</li>

// takenlijst_react/src/components/TaskItem.jsx
import { useState } from 'react';

function TaskItem({ taak, onRemove, onToggle, onUpdate }) {
  const [bewerkModus, setBewerkModus] = useState(false);
  const [bewerktitel, setBewerktitel] = useState('');

  // Annuleer Update
  function AnnuleerUpdate() { setBewerkModus(false); setBewerktitel(''); }

  // opslaan Update
  function opslaanUpdate() {
    const titel = bewerktitel.trim();
    if (!titel) return;
    onUpdate(taak.id, titel);
    setBewerkModus(false);
    setBewerktitel('');
  }

  return (
    <li className={`row prioriteit-${taak.prioriteit}`}>
      <input type="checkbox" checked={taak.done} onChange={() => onToggle(taak.id)} />
      {bewerkModus !== true ? (
        <>
          <span className={taak.done ? "titel done" : "titel"}>{taak.titel}</span>
          <div className="actions">
            <button onClick={() => { setBewerkModus(true); setBewerktitel(taak.titel); }}>Bewerk</button>
            <button onClick={() => onRemove(taak.id)}>Verwijder</button>
          </div>
        </>
      ) : (
        <>
          <input value={bewerktitel} onChange={(e) => setBewerktitel(e.target.value)} onKeyUp={(e) => e.key === 'Enter' && opslaanUpdate()} />
          <div className="actions">
            <button onClick={opslaanUpdate}>Opslaan</button>
            <button onClick={AnnuleerUpdate}>Annuleer</button>
          </div>
        </>
      )}
    </li>
  );
}

export default TaskItem;
