// takenlijst_vue/src/components/TaskItem.vue
<template>
  <li class="row" :class="`prioriteit-${taak.prioriteit}`">
    <input type="checkbox" :checked="taak.done" @change="onToggle(taak.id)"/>
    <span v-if="!bewerkModus" :class="{ done: taak.done }" class="titel">{{ taak.titel }}</span>
    <input v-else v-model="bewerktitel" @keyup.enter="opslaanUpdate" @keyup.esc="AnnuleerUpdate"/>
    <div class="actions" v-if="!bewerkModus">
      <button @click="startEdit">Bewerk</button>
      <button @click="onRemove(taak.id)">Verwijder</button>
    </div>
    <div class="actions" v-else>
      <button @click="opslaanUpdate">Opslaan</button>
      <button @click="AnnuleerUpdate">Annuleer</button>
    </div>
  </li>
</template>

<script setup>
import { ref } from 'vue';
const props = defineProps(['taak', 'onToggle', 'onRemove', 'onUpdate']);
const bewerkModus = ref(false);
const bewerktitel = ref('');

function startEdit() { bewerkModus.value = true; bewerktitel.value = props.taak.titel; }

// Annuleer Update
function AnnuleerUpdate() { bewerkModus.value = false; bewerktitel.value = ''; }

// opslaan Update
function opslaanUpdate() {
  const titel = bewerktitel.value.trim();
  if (!titel) return;
  props.onUpdate(props.taak.id, titel);
  bewerkModus.value = false;
  bewerktitel.value = '';
}
</script>

// takenlijst_svelte/src/components/TaskItem.svelte
<script>
  export let taak;
  export let onToggle;
  export let onRemove;
  export let onUpdate;

  let bewerkModus = false;
  let bewerktitel = '';

  function startBewerk() { bewerkModus = true; bewerktitel = taak.titel; }

  // Annuleer Update
  function AnnuleerUpdate() { bewerkModus = false; bewerktitel = ''; }

  // opslaan Update
  function opslaanUpdate() {
    const titel = bewerktitel.trim();
    if (!titel) return;
    onUpdate(taak.id, titel);
    bewerkModus = false;
    bewerktitel = '';
  }
</script>

<li class="row prioriteit-{taak.prioriteit}">
  <input type="checkbox" checked={taak.done} on:change={() => onToggle(taak.id)}/>
  {#if !bewerkModus}
    <span class="titel" class:done={taak.done}>{taak.titel}</span>
    <div class="actions">
      <button on:click={startBewerk}>Bewerk</button>
      <button on:click={() => onRemove(taak.id)}>Verwijder</button>
    </div>
  {:else}
    <input bind:value={bewerktitel} on:keyup={(e) => e.key === 'Enter' && opslaanUpdate()}/>
    <div class="actions">
      <button on:click={opslaanUpdate}>Opslaan</button>
      <button on:click={AnnuleerUpdate}>Annuleer</button>
    </div>
  {/if}
</li>
