// takenlijst_react/src/components/TaskList.jsx
import TaskItem from './TaskItem';

function TaskList({ taken, onRemove, onToggle, onUpdate }) {
  const items = [];
  for (let i = 0; i < taken.length; i++) {
    items.push(<TaskItem key={taken[i].id} taak={taken[i]} onRemove={onRemove} onToggle={onToggle} onUpdate={onUpdate}/>);
  }

  return (
    <div>
      <ul>{items}</ul>
      {taken.length === 0 && <p>Nog geen taken.</p>}
    </div>
  );
}

export default TaskList;

// takenlijst_svelte/src/components/TaskList.svelte
<script>
  import TaskItem from './TaskItem.svelte';

  export let taken = [];
  export let onToggle;
  export let onRemove;
  export let onUpdate;
</script>

<div>
  <ul>
    {#each taken as taak (taak.id)}
      <TaskItem {taak} {onToggle} {onRemove} {onUpdate}/>
    {/each}
  </ul>
  {#if taken.length === 0}
    <p>Nog geen taken.</p>
  {/if}
</div>
